// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_Nonu_Stefania_Popa_Raul.Data;

#nullable disable

namespace Proiect_Nonu_Stefania_Popa_Raul.Migrations
{
    [DbContext(typeof(Proiect_Nonu_Stefania_Popa_RaulContext))]
    [Migration("20260109213207_TabeleRentACar")]
    partial class TabeleRentACar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proiect_Nonu_Stefania_Popa_Raul.Models.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("Proiect_Nonu_Stefania_Popa_Raul.Models.Inchiriere", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataPreluare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReturnare")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MasinaID")
                        .HasColumnType("int");

                    b.Property<string>("NumeClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MasinaID");

                    b.ToTable("Inchiriere");
                });

            modelBuilder.Entity("Proiect_Nonu_Stefania_Popa_Raul.Models.Masina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BrandID")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PretPeZi")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("ID");

                    b.HasIndex("BrandID");

                    b.ToTable("Masina");
                });

            modelBuilder.Entity("Proiect_Nonu_Stefania_Popa_Raul.Models.Inchiriere", b =>
                {
                    b.HasOne("Proiect_Nonu_Stefania_Popa_Raul.Models.Masina", "Masina")
                        .WithMany("Inchirieri")
                        .HasForeignKey("MasinaID");

                    b.Navigation("Masina");
                });

            modelBuilder.Entity("Proiect_Nonu_Stefania_Popa_Raul.Models.Masina", b =>
                {
                    b.HasOne("Proiect_Nonu_Stefania_Popa_Raul.Models.Brand", "Brand")
                        .WithMany("Masini")
                        .HasForeignKey("BrandID");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Proiect_Nonu_Stefania_Popa_Raul.Models.Brand", b =>
                {
                    b.Navigation("Masini");
                });

            modelBuilder.Entity("Proiect_Nonu_Stefania_Popa_Raul.Models.Masina", b =>
                {
                    b.Navigation("Inchirieri");
                });
#pragma warning restore 612, 618
        }
    }
}
